### PR TITLE
Create a more visually pleasing format

### PR DESCRIPTION
**Pull request by Elfocrash**
Hey, good job on the repo. I do have a couple suggestions and I'll start with this one.
I think that the collapsing feature is not a good idea for a couple of reasons.
First, it kinda encourages people to only un-collapse the countries that they want, which in a way undermines the other ones. I think it would be better if every country was just uncollapsed and to make it more visually distinct the flag of the country was also shown. I also think it would be good to add the logo or face of each creator because it makes the page easier to read and some people might recognise faces easier than names.

I've only changed the format for the first 2 countries just to get your thoughts on the format.

### CODE REVIEW

**Comment by matthiasjost** [comment]
Hey Nick, thanks a lot for your feedback!

I agree that it is probably better to have it opened and not collapsable.

About the icons and flags, that seems like a good addition to make it visually more appealing.

Just something I noticed: How could we add the images so that the URLs are shorter and more consistent? Also, so that the image is easy to replace? Maybe in the folder in the repository itself?

I really appreciate those improvements! I will merge the PR when you think it makes sense to do so, already. Just tell me how you would like to proceed here.

Greetings

Matthias

**Comment by matthiasjost** [comment]
@Elfocrash Hey Nick, I updated the file to include all flags. I am not sure yet about the profile pictures for the creators. Not sure yet if it really adds that much value or if it raises the barrier to adding new entries too much.

**Comment by Elfocrash** [comment]
Hey @matthiasjost, sorry for not getting back to you earlier on this. Busy weekend.
I think it does make it better. I recognise faces more than logos and some people also use different username for their content (for example ardalis for Steve Smith) so the logo makes it way easier to differentiate.
If [awesome-youtubers](https://github.com/JoseDeFreitas/awesome-youtubers) can do it with way more creators then I think it's a good idea for this repo too. They go as far as to add content type, language, verification status etc, which is not something I think you should add necessarily, but it does invalidate the barrier to entry point.

**Comment by matthiasjost** [comment]
@Elfocrash Ok. That makes sense! Let us add those icons/logos then. Thanks for your feedback.

**Comment by matthiasjost** [comment]
@Elfocrash, Just realised would be a lot of work to gather all the images and bring them into a good format. Not sure yet how to do that efficiently.

**Comment by matthiasjost** [comment]
Created an issue here: #12

**Comment by dracan** [comment]
> @Elfocrash, Just realised would be a lot of work to gather all the images and bring them into a good format. Not sure yet how to do that efficiently.

I suspect it wouldn't be too bad once the layout of the page is sorted. I'm more than happy to help out, digging up various profile images and updating the page with them.

**Comment by matthiasjost** [comment]
@dracan, I think we would just add another column called an icon, as Nick suggested. Would be awesome if you could help here!

**Comment by dracan** [comment]
I wonder if this would be neater if the images were files in the Github repository, and the table was using markdown syntax for images, rather than HTML? So then the filename could just match the person's name, and it might look more like this...

```
| ![](/profilepics/les.png) | Les Jackson | [YouTube](https://www.youtube.com/c/binarythistle) |
```
Rather than resizing dynamically - a specific height for the file itself could just be a requirement in the PR. It keeps the markdown super-simple.

**Comment by matthiasjost** [comment]
That's an awesome idea!

**Comment by matthiasjost** [comment]
Please excuse when I closed the PR too early. I reopened the PR because we continued with the discussion here. I also opened an issue @dracan @Elfocrash 

https://github.com/matthiasjost/dotnet-content-creators/issues/12

**Comment by dracan** [comment]
I was wondering why it had been closed 😆

@Elfocrash - Are you happy with the above suggestion? I'm happy to make a start to get the ball rolling - but I don't want to change your work unless you're happy.

**Comment by matthiasjost** [comment]
> I was wondering why it had been closed 😆
> 
> @Elfocrash - Are you happy with the above suggestion? I'm happy to make a start to get the ball rolling - but I don't want to change your work unless you're happy.

I am new to contributing on GitHub and I thought I close it because I started to change the main branch with the suggestions about the flag.

I am looking forward to your feedback @Elfocrash and happy to see you contributing to this @dracan 🙏

**Pull request closed without merging**
